export const SET_LOGO = "SET_LOGO";
export const SET_NAME = "SET_NAME";
export const SET_USER_INFO = "SET_USER_INFO";
export const SET_USER_PERMISSION = "SET_USER_PERMISSION";

export const SET_INCHARGE = "SET_INCHARGE";
export const SET_MOP = "SET_MOP";
export const GET_SUPPLIERS = "GET_SUPPLIERS";
export const GET_NOTIFICATION_LIST = "GET_NOTIFICATION_LIST";
export const GET_NOTIFICATION_LIST_BYDEPT = "GET_NOTIFICATION_LIST_BYDEPT";

export const GET_DEFAULTS = "GET_DEFAULTS";
export const   SIGNALR_CONNECT_NOTIFY ="SIGNALR_CONNECT_NOTIFY"
export const FILE_URL = "http://172.17.144.31:45457/";


export const SET_SNACKBAR = "SET_SNACKBAR";

export const SET_GLOBAL_SNACKBAR = "SET_GLOBAL_SNACKBAR";
export const SET_PERMISSIONS = "SET_PERMISSIONS";
