export const SET_INVENTORY_TABLE = "SET_INVENTORY_TABLE";
export const GET_INVENTORY_DEPARTMENT = "GET_INVENTORY_DEPARTMENT";
export const GET_NON_INVENTORY = "GET_NON_INVENTORY";
export const SET_OFFICE = "SET_OFFICE";
export const SET_OPEN_MODAL = "SET_OPEN_MODAL";
export const SET_OPEN_QTYMODAL = "SET_OPEN_QTYMODAL";
export const SET_SELECTED_ITEM = "SET_SELECTED_ITEM";
export const SET_REQ_DTLS = "SET_REQ_DTLS";
export const SET_REQ_FOOTER = "SET_REQ_FOOTER";
export const SET_REQ_HEADER = "SET_REQ_HEADER";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const GET_REQUEST_INFO = "GET_REQUEST_INFO";
export const GET_SINGLEREQUEST_HEADER = "GET_SINGLEREQUEST_HEADER";
export const GET_SINGLEREQUEST_DETAILS = "GET_SINGLEREQUEST_DETAILS";

export const SET_INVENTORY_TABLE_BYSTATUS = "SET_INVENTORY_TABLE_BYSTATUS";
export const GET_DASHBOARD_NUMBERS = "GET_DASHBOARD_NUMBERS";
export const SET_STATUS_FOR_TABLE = "SET_STATUS_FOR_TABLE";
export const SET_SEARCH_FOR_TABLE = "SET_SEARCH_FOR_TABLE";
export const SET_SEARCH_TABLE_PER_ITEM = "SET_SEARCH_TABLE_PER_ITEM";

export const SET_SEARCH_FOR_STOCKCLASS = "SET_SEARCH_FOR_STOCKCLASS";
export const SET_STOCK_CLASS = "SET_STOCK_CLASS";
