export const SET_DATA = "SET_DATA";
export const SET_DEPARTMENTS = "SET_DEPARTMENTS";
export const SET_PRTYPE = "SET_PRTYPE";
export const SET_PR_ITEMS = "SET_PR_ITEMS";
export const SET_NONPR_ITEMS = "SET_NONPR_ITEMS";
export const SET_SOURCE_PPMP_LIST = "SET_SOURCE_PPMP_LIST";
export const SET_DATA_OTHERS_DEPT = "SET_DATA_OTHERS_DEPT";
export const GET_PPMP_ALREADY_REQUESTED_BUDGET =
  "GET_PPMP_ALREADY_REQUESTED_BUDGET";
export const GET_PPMP_TOTAL_BUDGET = "GET_PPMP_TOTAL_BUDGET";
export const SET_CURRENT_QTY_ITEMS = "SET_CURRENT_QTY_ITEMS";
export const GET_PR_NO = "GET_PR_NO";
export const GET_PR_DETAILS = "GET_PR_DETAILS";
export const GET_PR_DETAILS_QTY_CHILD = "GET_PR_DETAILS_QTY_CHILD";

export const SET_APPROVED = "SET_APPROVED";
export const SET_RECEIVED = "SET_RECEIVED";
export const SET_CANCELLED = "SET_CANCELLED";
